# Generated by Django 3.2.4 on 2021-07-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('fee', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='learnera/images')),
                ('video_link', models.URLField()),
            ],
        ),
    ]
