# Generated by Django 3.2.4 on 2021-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
