# Generated by Django 3.2.4 on 2021-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0002_alter_allcourse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourse',
            name='sort_desc',
            field=models.CharField(default='Sort Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='allcourse',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
