# Generated by Django 3.2.4 on 2021-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0003_auto_20210704_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='sort_desc',
            field=models.CharField(max_length=200),
        ),
    ]
