# Generated by Django 3.2.4 on 2021-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0004_alter_allcourse_sort_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='desc',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='allcourse',
            name='sort_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
