# Generated by Django 3.2.4 on 2021-07-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0005_auto_20210705_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('picture_url', models.URLField(max_length=120)),
                ('u_id', models.CharField(max_length=120)),
            ],
        ),
    ]
