# Generated by Django 3.2.4 on 2021-07-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnera', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
